CREATE TABLE Usuario (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    perfil_id INT REFERENCES Perfil(id) ON DELETE CASCADE
);
ALTER TABLE Comanda
ADD CONSTRAINT fk_usuario
FOREIGN KEY (id_usuario) REFERENCES Usuario(id);